# Generated by Django 5.0.4 on 2024-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vertiport',
            fields=[
                ('name', models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('fato', models.SmallIntegerField(default=0)),
                ('path_in', models.SmallIntegerField(default=0)),
                ('gate', models.SmallIntegerField(default=0)),
                ('path_out', models.SmallIntegerField(default=0)),
                ('waiting_room', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'vertiport',
            },
        ),
    ]
