# Generated by Django 5.0.4 on 2024-05-10 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vertiports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('fato_in_UAM', models.SmallIntegerField(default=0)),
                ('path_in_UAM', models.SmallIntegerField(default=0)),
                ('gate_UAM', models.SmallIntegerField(default=0)),
                ('path_out_UAM', models.SmallIntegerField(default=0)),
                ('fato_out_UAM', models.SmallIntegerField(default=0)),
                ('gate_UAM_psg', models.SmallIntegerField(default=0)),
                ('waiting_room_psg', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vertiport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertiports.vertiport')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fato_in_UAM', models.SmallIntegerField(default=0)),
                ('path_in_UAM', models.SmallIntegerField(default=0)),
                ('gate_UAM', models.SmallIntegerField(default=0)),
                ('path_out_UAM', models.SmallIntegerField(default=0)),
                ('fato_out_UAM', models.SmallIntegerField(default=0)),
                ('gate_UAM_psg', models.SmallIntegerField(default=0)),
                ('waiting_room_psg', models.SmallIntegerField(default=0)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizations.state')),
            ],
            options={
                'db_table': 'optimization',
            },
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('sequence', 'user', 'vertiport'), name='state_composite_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='optimization',
            constraint=models.UniqueConstraint(fields=('weight', 'state'), name='optimization_composite_primary_key'),
        ),
    ]
